### ISSUE TITLE
Upgrade for 2.x

### ISSUE THREAD

**Issue by mark-cooper** [archivesspace/aeon_requests#5]
Incompatible with 2.x: `undefined method `concat' for nil:NilClass from ... aeon_requests/public/plugin_init.rb:2:in`.

Needs at least:

```ruby
ArchivesSpace::Application.extend_aspace_routes(File.join(File.dirname(__FILE__), "routes.rb"))
```

**Comment by ballin22s** [comment]
so if i replace the current code with the code above it should work?

**Comment by mark-cooper** [comment]
https://github.com/archivesspace-plugins/aeon_requests/pull/6
